//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseExport.SurveyManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SurveyManagementService.ISurveyManagementService")]
    public interface ISurveyManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/ListSurveysAndFolders", ReplyAction="http://tempuri.org/ISurveyManagementService/ListSurveysAndFoldersResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]> ListSurveysAndFolders(string authTicket, int parentId, bool includeSurveyResponseCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/ListAvailableSurveys", ReplyAction="http://tempuri.org/ISurveyManagementService/ListAvailableSurveysResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>> ListAvailableSurveys(string authTicket, int pageNumber, int pageSize, string sortField, bool sortAscending, string filterField, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetSurveyListItem", ReplyAction="http://tempuri.org/ISurveyManagementService/GetSurveyListItemResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem> GetSurveyListItem(string authTicket, int listItemId, string listItemType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetSurveyMetaData", ReplyAction="http://tempuri.org/ISurveyManagementService/GetSurveyMetaDataResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData> GetSurveyMetaData(string authTicket, int surveyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetSurveyInfoByGuid", ReplyAction="http://tempuri.org/ISurveyManagementService/GetSurveyInfoByGuidResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData> GetSurveyInfoByGuid(string authTicket, System.Guid rtGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetSurveyInfoByName", ReplyAction="http://tempuri.org/ISurveyManagementService/GetSurveyInfoByNameResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData> GetSurveyInfoByName(string authTicket, string surveyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/AddUserToSurveyAccessList", ReplyAction="http://tempuri.org/ISurveyManagementService/AddUserToSurveyAccessListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> AddUserToSurveyAccessList(string authTicket, string uniqueIdentifier, int responseTemplateID, string[] permissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetSurveyPageData", ReplyAction="http://tempuri.org/ISurveyManagementService/GetSurveyPageDataResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData> GetSurveyPageData(string authTicket, int surveyId, int pageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/IfAlternateUrlIsAvailable", ReplyAction="http://tempuri.org/ISurveyManagementService/IfAlternateUrlIsAvailableResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult> IfAlternateUrlIsAvailable(string authTicket, string customUrl, string serverApplicationPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetSurveyItemData", ReplyAction="http://tempuri.org/ISurveyManagementService/GetSurveyItemDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> GetSurveyItemData(string authTicket, int surveyId, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetConditionDataForSurveyPage", ReplyAction="http://tempuri.org/ISurveyManagementService/GetConditionDataForSurveyPageResponse" +
            "")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData> GetConditionDataForSurveyPage(string authTicket, int surveyId, int pageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetBranchDataForSurveyPage", ReplyAction="http://tempuri.org/ISurveyManagementService/GetBranchDataForSurveyPageResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]> GetBranchDataForSurveyPage(string authTicket, int surveyId, int pageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetConditionDataForSurveyItem", ReplyAction="http://tempuri.org/ISurveyManagementService/GetConditionDataForSurveyItemResponse" +
            "")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData> GetConditionDataForSurveyItem(string authTicket, int surveyId, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetLibraryItemData", ReplyAction="http://tempuri.org/ISurveyManagementService/GetLibraryItemDataResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> GetLibraryItemData(string authTicket, int libraryId, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/ListSurveyStyleTemplates", ReplyAction="http://tempuri.org/ISurveyManagementService/ListSurveyStyleTemplatesResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>> ListSurveyStyleTemplates(string authTicket, int pageNumber, int pageSize, string sortField, bool sortAscending, string filterField, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/ListItemLibraries", ReplyAction="http://tempuri.org/ISurveyManagementService/ListItemLibrariesResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>> ListItemLibraries(string authTicket, int pageNumber, int pageSize, string sortField, bool sortAscending, string filterField, string filterValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/GetLibraryData", ReplyAction="http://tempuri.org/ISurveyManagementService/GetLibraryDataResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData> GetLibraryData(string authTicket, int libraryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/DeleteFolder", ReplyAction="http://tempuri.org/ISurveyManagementService/DeleteFolderResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool> DeleteFolder(string authTicket, int folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/DeleteSurvey", ReplyAction="http://tempuri.org/ISurveyManagementService/DeleteSurveyResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool> DeleteSurvey(string authTicket, int surveyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/DeleteLibraries", ReplyAction="http://tempuri.org/ISurveyManagementService/DeleteLibrariesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteLibraries(string authTicket, int[] libraryIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/MoveSurveyItem", ReplyAction="http://tempuri.org/ISurveyManagementService/MoveSurveyItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> MoveSurveyItem(string authToken, int responseTemplateId, int itemId, System.Nullable<int> newPageId, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/AddSurveyPage", ReplyAction="http://tempuri.org/ISurveyManagementService/AddSurveyPageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> AddSurveyPage(string authToken, int responseTemplateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/MoveSurveyPage", ReplyAction="http://tempuri.org/ISurveyManagementService/MoveSurveyPageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> MoveSurveyPage(string authToken, int responseTemplateId, int pageId, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/CopySurveyPage", ReplyAction="http://tempuri.org/ISurveyManagementService/CopySurveyPageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> CopySurveyPage(string authTicket, int surveyId, int pageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/DeleteSurveyPage", ReplyAction="http://tempuri.org/ISurveyManagementService/DeleteSurveyPageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteSurveyPage(string authTicket, int surveyId, int pageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/DeleteSurveyItem", ReplyAction="http://tempuri.org/ISurveyManagementService/DeleteSurveyItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteSurveyItem(string authTicket, int surveyId, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/AddResponsePipeToSurvey", ReplyAction="http://tempuri.org/ISurveyManagementService/AddResponsePipeToSurveyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyPageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PageMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ExpressionMetaData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.RuleMetaData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.StyleListItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LibraryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> AddResponsePipeToSurvey(string authTicket, int surveyId, int itemId, string pipeValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManagementService/Search", ReplyAction="http://tempuri.org/ISurveyManagementService/SearchResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]> Search(string authTicket, string searchTerm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISurveyManagementServiceChannel : ResponseExport.SurveyManagementService.ISurveyManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SurveyManagementServiceClient : System.ServiceModel.ClientBase<ResponseExport.SurveyManagementService.ISurveyManagementService>, ResponseExport.SurveyManagementService.ISurveyManagementService {
        
        public SurveyManagementServiceClient() {
        }
        
        public SurveyManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SurveyManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]> ListSurveysAndFolders(string authTicket, int parentId, bool includeSurveyResponseCount) {
            return base.Channel.ListSurveysAndFolders(authTicket, parentId, includeSurveyResponseCount);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.SurveyListItem[]>> ListAvailableSurveys(string authTicket, int pageNumber, int pageSize, string sortField, bool sortAscending, string filterField, string filterValue) {
            return base.Channel.ListAvailableSurveys(authTicket, pageNumber, pageSize, sortField, sortAscending, filterField, filterValue);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyListItem> GetSurveyListItem(string authTicket, int listItemId, string listItemType) {
            return base.Channel.GetSurveyListItem(authTicket, listItemId, listItemType);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData> GetSurveyMetaData(string authTicket, int surveyId) {
            return base.Channel.GetSurveyMetaData(authTicket, surveyId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData> GetSurveyInfoByGuid(string authTicket, System.Guid rtGuid) {
            return base.Channel.GetSurveyInfoByGuid(authTicket, rtGuid);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyMetaData> GetSurveyInfoByName(string authTicket, string surveyName) {
            return base.Channel.GetSurveyInfoByName(authTicket, surveyName);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> AddUserToSurveyAccessList(string authTicket, string uniqueIdentifier, int responseTemplateID, string[] permissions) {
            return base.Channel.AddUserToSurveyAccessList(authTicket, uniqueIdentifier, responseTemplateID, permissions);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.SurveyPageMetaData> GetSurveyPageData(string authTicket, int surveyId, int pageId) {
            return base.Channel.GetSurveyPageData(authTicket, surveyId, pageId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.QuestionResult> IfAlternateUrlIsAvailable(string authTicket, string customUrl, string serverApplicationPath) {
            return base.Channel.IfAlternateUrlIsAvailable(authTicket, customUrl, serverApplicationPath);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> GetSurveyItemData(string authTicket, int surveyId, int itemId) {
            return base.Channel.GetSurveyItemData(authTicket, surveyId, itemId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData> GetConditionDataForSurveyPage(string authTicket, int surveyId, int pageId) {
            return base.Channel.GetConditionDataForSurveyPage(authTicket, surveyId, pageId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData[]> GetBranchDataForSurveyPage(string authTicket, int surveyId, int pageId) {
            return base.Channel.GetBranchDataForSurveyPage(authTicket, surveyId, pageId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.RuleMetaData> GetConditionDataForSurveyItem(string authTicket, int surveyId, int itemId) {
            return base.Channel.GetConditionDataForSurveyItem(authTicket, surveyId, itemId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> GetLibraryItemData(string authTicket, int libraryId, int itemId) {
            return base.Channel.GetLibraryItemData(authTicket, libraryId, itemId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.StyleListItem[]>> ListSurveyStyleTemplates(string authTicket, int pageNumber, int pageSize, string sortField, bool sortAscending, string filterField, string filterValue) {
            return base.Channel.ListSurveyStyleTemplates(authTicket, pageNumber, pageSize, sortField, sortAscending, filterField, filterValue);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.LibraryData[]>> ListItemLibraries(string authTicket, int pageNumber, int pageSize, string sortField, bool sortAscending, string filterField, string filterValue) {
            return base.Channel.ListItemLibraries(authTicket, pageNumber, pageSize, sortField, sortAscending, filterField, filterValue);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.LibraryData> GetLibraryData(string authTicket, int libraryId) {
            return base.Channel.GetLibraryData(authTicket, libraryId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool> DeleteFolder(string authTicket, int folderId) {
            return base.Channel.DeleteFolder(authTicket, folderId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<bool> DeleteSurvey(string authTicket, int surveyId) {
            return base.Channel.DeleteSurvey(authTicket, surveyId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteLibraries(string authTicket, int[] libraryIds) {
            return base.Channel.DeleteLibraries(authTicket, libraryIds);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> MoveSurveyItem(string authToken, int responseTemplateId, int itemId, System.Nullable<int> newPageId, int position) {
            return base.Channel.MoveSurveyItem(authToken, responseTemplateId, itemId, newPageId, position);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> AddSurveyPage(string authToken, int responseTemplateId) {
            return base.Channel.AddSurveyPage(authToken, responseTemplateId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> MoveSurveyPage(string authToken, int responseTemplateId, int pageId, int position) {
            return base.Channel.MoveSurveyPage(authToken, responseTemplateId, pageId, position);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> CopySurveyPage(string authTicket, int surveyId, int pageId) {
            return base.Channel.CopySurveyPage(authTicket, surveyId, pageId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteSurveyPage(string authTicket, int surveyId, int pageId) {
            return base.Channel.DeleteSurveyPage(authTicket, surveyId, pageId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteSurveyItem(string authTicket, int surveyId, int itemId) {
            return base.Channel.DeleteSurveyItem(authTicket, surveyId, itemId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> AddResponsePipeToSurvey(string authTicket, int surveyId, int itemId, string pipeValue) {
            return base.Channel.AddResponsePipeToSurvey(authTicket, surveyId, itemId, pipeValue);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.SurveyListItem>[]> Search(string authTicket, string searchTerm) {
            return base.Channel.Search(authTicket, searchTerm);
        }
    }
}
