
package com.checkbox.ftpresponseexporter.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAuthenticationService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAuthenticationService {


    /**
     * 
     * @return
     *     returns com.checkbox.ServiceOperationResultOfboolean
     */
    @WebMethod(operationName = "IsLoggedIn", action = "http://tempuri.org/IAuthenticationService/IsLoggedIn")
    @WebResult(name = "IsLoggedInResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsLoggedIn", targetNamespace = "http://tempuri.org/", className = "com.checkbox.IsLoggedIn")
    @ResponseWrapper(localName = "IsLoggedInResponse", targetNamespace = "http://tempuri.org/", className = "com.checkbox.IsLoggedInResponse")
    public ServiceOperationResultOfboolean isLoggedIn();

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns com.checkbox.ServiceOperationResultOfstring
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/IAuthenticationService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "com.checkbox.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "com.checkbox.LoginResponse")
    public ServiceOperationResultOfstring login(
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
            String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
            String password);

    /**
     * 
     * @return
     *     returns com.checkbox.ServiceOperationResultOfanyType
     */
    @WebMethod(operationName = "Logout", action = "http://tempuri.org/IAuthenticationService/Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://tempuri.org/", className = "com.checkbox.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://tempuri.org/", className = "com.checkbox.LogoutResponse")
    public ServiceOperationResultOfanyType logout();

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns com.checkbox.ServiceOperationResultOfboolean
     */
    @WebMethod(operationName = "ValidateUser", action = "http://tempuri.org/IAuthenticationService/ValidateUser")
    @WebResult(name = "ValidateUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidateUser", targetNamespace = "http://tempuri.org/", className = "com.checkbox.ValidateUser")
    @ResponseWrapper(localName = "ValidateUserResponse", targetNamespace = "http://tempuri.org/", className = "com.checkbox.ValidateUserResponse")
    public ServiceOperationResultOfboolean validateUser(
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
            String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
            String password);

}
