//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseExport_Console.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseData
    {
        public int Id { get; set; }
        public int ResponseId { get; set; }
        public string ResponseGuid { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public string TotalTime { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public string IP { get; set; }
        public string Language { get; set; }
        public string UniqueIdentifier { get; set; }
        public string Invitee { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Item1526 { get; set; }
        public string Item1527 { get; set; }
    }
}
