//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseExport.ResponseDataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResponseDataService.IResponseDataService")]
    public interface IResponseDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetSurveyResponseSummary", ReplyAction="http://tempuri.org/IResponseDataService/GetSurveyResponseSummaryResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseSummaryData> GetSurveyResponseSummary(string authTicket, int surveyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ListRecentSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/ListRecentSurveyResponsesResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseData[]> ListRecentSurveyResponses(string authTicket, int surveyId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/UpdateResponseAnswer", ReplyAction="http://tempuri.org/IResponseDataService/UpdateResponseAnswerResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseSummaryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseSummaryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.AggregateResult[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ReportResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemProxyObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> UpdateResponseAnswer(string authToken, int surveyId, long responseId, long answerId, string answerText, System.Nullable<int> optionID, System.Nullable<System.DateTime> dateCreated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ListSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/ListSurveyResponsesResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>> ListSurveyResponses(string authTicket, int surveyId, int pageNumber, int resultsPerPage, string filterField, string filterValue, string sortField, bool sortAscending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/DeleteSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/DeleteSurveyResponsesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseSummaryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseSummaryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.AggregateResult[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ReportResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemProxyObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteSurveyResponses(string authTicket, int surveyId, long[] responseList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/DeleteAllSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/DeleteAllSurveyResponsesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseSummaryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseSummaryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.AggregateResult[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ReportResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemProxyObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteAllSurveyResponses(string authTicket, int surveyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/DeleteAllSurveyTestResponses", ReplyAction="http://tempuri.org/IResponseDataService/DeleteAllSurveyTestResponsesResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseSummaryData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseSummaryData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.AggregateResult[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ReportResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemProxyObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(long[]))]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteAllSurveyTestResponses(string authTicket, int surveyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/Search", ReplyAction="http://tempuri.org/IResponseDataService/SearchResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]> Search(string authTicket, string searchTerm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInMonths", ReplyAction="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInMonthsResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string> GetLifecycleResponseDataInMonths(string authTicket, int surveyId, int numberOfRecentMonths);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInDays", ReplyAction="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInDaysResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string> GetLifecycleResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetLifecycleAggregatedResponseDataInDays", ReplyAction="http://tempuri.org/IResponseDataService/GetLifecycleAggregatedResponseDataInDaysR" +
            "esponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.AggregateResult[]> GetLifecycleAggregatedResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetAnswersForResponseByGuid", ReplyAction="http://tempuri.org/IResponseDataService/GetAnswersForResponseByGuidResponse")]
        Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]> GetAnswersForResponseByGuid(string authTicket, int surveyId, string languageCode, System.Guid responseGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResponseDataServiceChannel : ResponseExport.ResponseDataService.IResponseDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResponseDataServiceClient : System.ServiceModel.ClientBase<ResponseExport.ResponseDataService.IResponseDataService>, ResponseExport.ResponseDataService.IResponseDataService {
        
        public ResponseDataServiceClient() {
        }
        
        public ResponseDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResponseDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResponseDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResponseDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseSummaryData> GetSurveyResponseSummary(string authTicket, int surveyId) {
            return base.Channel.GetSurveyResponseSummary(authTicket, surveyId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseData[]> ListRecentSurveyResponses(string authTicket, int surveyId, int count) {
            return base.Channel.ListRecentSurveyResponses(authTicket, surveyId, count);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> UpdateResponseAnswer(string authToken, int surveyId, long responseId, long answerId, string answerText, System.Nullable<int> optionID, System.Nullable<System.DateTime> dateCreated) {
            return base.Channel.UpdateResponseAnswer(authToken, surveyId, responseId, answerId, answerText, optionID, dateCreated);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.PagedListResult<Checkbox.Wcf.Services.Proxies.ResponseData[]>> ListSurveyResponses(string authTicket, int surveyId, int pageNumber, int resultsPerPage, string filterField, string filterValue, string sortField, bool sortAscending) {
            return base.Channel.ListSurveyResponses(authTicket, surveyId, pageNumber, resultsPerPage, filterField, filterValue, sortField, sortAscending);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteSurveyResponses(string authTicket, int surveyId, long[] responseList) {
            return base.Channel.DeleteSurveyResponses(authTicket, surveyId, responseList);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteAllSurveyResponses(string authTicket, int surveyId) {
            return base.Channel.DeleteAllSurveyResponses(authTicket, surveyId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<object> DeleteAllSurveyTestResponses(string authTicket, int surveyId) {
            return base.Channel.DeleteAllSurveyTestResponses(authTicket, surveyId);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.GroupedResult<Checkbox.Wcf.Services.Proxies.ResponseData>[]> Search(string authTicket, string searchTerm) {
            return base.Channel.Search(authTicket, searchTerm);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string> GetLifecycleResponseDataInMonths(string authTicket, int surveyId, int numberOfRecentMonths) {
            return base.Channel.GetLifecycleResponseDataInMonths(authTicket, surveyId, numberOfRecentMonths);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<string> GetLifecycleResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods) {
            return base.Channel.GetLifecycleResponseDataInDays(authTicket, surveyId, periodLengthInDays, numberOfPeriods);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.AggregateResult[]> GetLifecycleAggregatedResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods) {
            return base.Channel.GetLifecycleAggregatedResponseDataInDays(authTicket, surveyId, periodLengthInDays, numberOfPeriods);
        }
        
        public Checkbox.Wcf.Services.Proxies.ServiceOperationResult<Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]> GetAnswersForResponseByGuid(string authTicket, int surveyId, string languageCode, System.Guid responseGuid) {
            return base.Channel.GetAnswersForResponseByGuid(authTicket, surveyId, languageCode, responseGuid);
        }
    }
}
